[TASK4] added 4th blocks
NikitaKhadnevich/iTechArt pull request #5
Opened 2021-10-29 14:14 UTC by NikitaKhadnevich

Added tasks which work with async-code,
created html-wrapper for demo,
configure some css-style file for work

2021-11-01 12:33 UTC, k-krasilnikova requested changes
Some updates required!

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index3.js
> +generatorHelper = () => number = Math.floor(Math.random()*10)*1000;
magic number!!!
Move it please to a separate constant with a readable name.

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index3.js
> +        delay <= 2000 ? resolve() : reject()
magic number!!!
Move it please to a separate constant with a readable name.

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index4.js
> +   if (response.status == 200) {
Let's create a separate constant with some http statuses to avoid using of magic numbers

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index4.js
> +   let response = await fetch(url)
Please don't forget to insert semicolumns at the end of the lines. Why `let` here?

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index4.js
> +      throw new HttpError(response)
Please don't forget to insert semicolumns at the end of the lines

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index4.js
> +      const responses = await response.json()
It's pretty hard to navigate between `responses` and `response`. Rename one of the variable/ or both of them to something more readable.

2021-11-01 12:33 UTC, k-krasilnikova commented on task4/index4.js
> +
Semicolumns

2021-11-01 16:48 UTC, NikitaKhadnevich commented on task4/index3.js
> +generatorHelper = () => number = Math.floor(Math.random()*10)*1000;
Add another const and rebuild generatorHelper-fnc

2021-11-01 16:48 UTC, NikitaKhadnevich commented on task4/index3.js
> +        delay <= 2000 ? resolve() : reject()
Added new const

2021-11-01 16:48 UTC, NikitaKhadnevich commented on task4/index4.js
> +   let response = await fetch(url)
it was replace let to const

2021-11-01 16:49 UTC, NikitaKhadnevich commented on task4/index4.js
> +   if (response.status == 200) {
Added new const with value 200, replaced old value

2021-11-01 16:49 UTC, NikitaKhadnevich commented on task4/index4.js
> +      const responses = await response.json()
Renamed responses to gitUsers

2021-11-01 16:49 UTC, NikitaKhadnevich commented on task4/index4.js
> +      throw new HttpError(response)
Added

2021-11-01 16:49 UTC, NikitaKhadnevich commented on task4/index4.js
> +
Added again

2021-11-02 13:10 UTC, k-krasilnikova approved these changes

2021-11-02 16:46 UTC, merged