[HTML_CSS Block | TASK 2-3]  There is 2 task.
NikitaKhadnevich/iTechArt pull request #6
Opened 2021-11-02 19:13 UTC by NikitaKhadnevich

### This pull request include a great number of code strings):
- added html-file which include html-elems like as div with classes, article, footer, main, p and other, also required dependencies for BEM;
- created scss files for comfortable work;
- also added js-file, and some note in js-file;
- There were rebuilt repository folders.

2021-11-08 07:36 UTC, k-krasilnikova requested changes
Pretty good job!
But some changes are required. 
And more:
1. Set please cursor: pointer for all buttons/arrows(slider and gallery)
2. Add please favicon to the site!

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const ARRDATA =
Wt if I ll wrt commnts th sam wy?
What is `ARRDATA` here? In case we will need to use one more array, it will be named like `ARRDATA2`? 
Rename please to something more clear, `SLIDER_IMAGES`, for example.

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const INITFORSLIDER = 0;
`INITIAL_VALUE_SLIDER`

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    if (state == 0) {
use from contant please

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +      wrapper.backgroundColor = '#f06c64';
Move colors to constant please
`const COLORS = {...}`

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +        console.log('COUNTER STATE', COUNTER);
Remove `console` please

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +        console.log('COUNTER STATE', COUNTER);
Remove `console` please

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const renderImage = (obj) => {  //5. created render-func as same as renderCount above ^^^^
What is `obj` in existed context?
Rename to something more clear

2021-11-08 07:36 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    for (var i = 0; i < elems.length; i++) {
I'm not sure that `var` should be here...
What is `elems`? Can you please rename all "common" variables to something referenced to the context of developed site

2021-11-08 15:39 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const ARRDATA =
Ok, Renamed already

2021-11-08 15:39 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const INITFORSLIDER = 0;
Done

2021-11-08 15:39 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    if (state == 0) {
Fixed its wrong

2021-11-08 15:40 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +      wrapper.backgroundColor = '#f06c64';
Created 2 obj with particular params

2021-11-08 15:40 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +        console.log('COUNTER STATE', COUNTER);
Done

2021-11-08 15:40 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +  const renderImage = (obj) => {  //5. created render-func as same as renderCount above ^^^^
Rename otherwise

2021-11-08 15:41 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    for (var i = 0; i < elems.length; i++) {
Done var => let and replaced name

2021-11-11 07:13 UTC, k-krasilnikova approved these changes
Good job!
Fix please one more comment and PR can be merged

2021-11-11 07:13 UTC, k-krasilnikova commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    if (e.target.id == burgerButton.id && burgerButton.checked == true) {
There is no need to check condition for true or false. Just replace it with:
`e.target.id == burgerButton.id && burgerButton.checked` or `e.target.id == burgerButton.id && !burgerButton.checked`

2021-11-11 10:22 UTC, NikitaKhadnevich commented on HTML_CSS_Block_SingoLogo/js/index.js
> +    if (e.target.id == burgerButton.id && burgerButton.checked == true) {
Fixed!

2021-11-11 10:28 UTC, merged