Added Readme
NikitaKhadnevich/iTechArt pull request #7
Opened 2021-11-15 13:04 UTC by NikitaKhadnevich

2021-11-16 08:39 UTC, k-krasilnikova requested changes

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +const ButtonChange = (props) => {
Pretty strange name of the component. Let's rename it to something more clear(Example: `EditButton`)

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +  const { id, changeNote, callToEditNote, noteList } = props;
There is no need to define an additional constants at the new line:
`const ButtonChange = ({ id, changeNote, callToEditNote, noteList }) => {`

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +    </>
No need to wrap `IconButton` with an additional empty tag

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +export const ButtonSaveChanges = (props) => {
Only one component per file!
You can move all the actions to a separate files: `components/notes/ActionButtons/SaveButton/SaveButton.jsx`
`components/notes/ActionButtons/EditButton/EditButton.jsx`
`components/notes/ActionButtons/RemoveButton/RemoveButton.jsx`
And compose them inside `components/notes/ActionButtons/ActionButtons.jsx`

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +export const ButtonSaveChanges = (props) => {
Define all the props inside params by destructing it

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +    <>
Remove please empty tag

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +          onClick={() => deleteNotes(index)}
`deleteNote`, only one..

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +const InputChange = ({
Separate folder for each component please!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +import { ButtonSaveChanges, ButtonDelete } from './ActionButtons';
If we're talking about imports, they separated by 3 categories:
```
libraries

absolute paths

relative paths
```
Example:
```
import React, { useState } from "react";
import Box from "@mui/material/Box";

import useStyles from 'pages/mainNotes/listNotes/styled';

import { ButtonSaveChanges, ButtonDelete } from './ActionButtons';
```
1. Setup absolute paths for pages, config, components folders
2. Sort imports by category

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const classes = useStyles();
Import please from `styled` file already prepared classes, or wrap component with MUi `useStyles` to avoid getting classes in separate constant

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const [newInputState, setNewInputState] = useState(description);
Is there any cases for setting old state?
No need to write new, and also inout, here we can set 100000 inputs and what will be the differences?
```suggestion
  const [updatedDescription, setDescription] = useState(description);
```

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const sendNewValue = (e) => {
old value?
what is value?
Rename please to something more clear

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +        style={{ marginLeft: '0px' }}
Move all the styles to a separate file

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/header/HeaderNav.jsx
> +    <>
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/header/HeaderNav.jsx
> +  const classes = useStyles();
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/header/HeaderNavCont.jsx
> +  <>
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +    const sortDescription = mainNotes.filter((item) => item.isActive);
I'm not sure that it's a good practice to save result in array, try to get directly selected object.

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +    <>
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    setNoteList(() => [...filtredNotes]);
Why did you use arrow function inside `setNoteList`? Why did you add rest prop?
```suggestion
    setNoteList(filtredNotes);
```

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    setNoteList(() => [...actualNotes]);
?

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    setNoteList(() => [...savedNotes]);
?

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    <>
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +                        {item.description.slice(0, SHORT_DESC.limit)}
Move it please to the `utils/index.js` and call here just function for cutting content

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +                    key={Math.random()}
I'm not sure it's a good idea

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +const AboutNote = React.lazy(() => import('./aboutNote/AboutNote'));
We can create index.jsx files inside mainNotes/ListNotes and MainNotes/AboutNotes folders that will contain lazy loading. So there is no need to overload container with such types of imports

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +import React, { useState, Suspense } from 'react';
What is mainNotesCont? Container? Contributor?

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +    <>
!

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +      </article>
You should define it's container or component.... logic in container, UI(only) inside the component

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/utils/CallToEditNote.jsx
> +  let arrNoteReciever = [...matchSource];
Why rest again?

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +  let arrNoteReciever = [...matchSource];
?

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +const chooseNote = (itemId, matchSource) => {
No need to create for each util new file, we can define all of them in one:
```
export const choose note ...
export const callEditNote ...
```

2021-11-16 08:39 UTC, k-krasilnikova commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +  const toggleItem = (arr, id) => {
arr?

2021-11-16 15:15 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    setNoteList(() => [...filtredNotes]);
I thought that would use 'prev => ...prev' , but its isnt my case, after some time i refused it and.... forgot to fix

2021-11-16 15:48 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +const AboutNote = React.lazy(() => import('./aboutNote/AboutNote'));
Added new jsx files and put Lazy

2021-11-16 15:54 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +      </article>
Its Container ,fixed

2021-11-16 15:56 UTC, NikitaKhadnevich commented on React_Notes_Block/src/utils/CallToEditNote.jsx
> +  let arrNoteReciever = [...matchSource];
Fixed, I thing its is not bind with prev => ..prev, Its realy my mistake as like in Handler-func (

2021-11-16 15:56 UTC, NikitaKhadnevich commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +  let arrNoteReciever = [...matchSource];
Fixed

2021-11-16 16:09 UTC, NikitaKhadnevich commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +const chooseNote = (itemId, matchSource) => {
Yes, these are similar function, but each of them change different params = callToEdit works with  **...note, isActive: !note.isActive, isChange: !note.isChange ,**
chooseNote works with  **...note, isActive: !note.isActive, isChange: false** . There is important for styles and note appearance. Maybe will remain these function?

2021-11-16 16:14 UTC, NikitaKhadnevich commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +  const toggleItem = (arr, id) => {
renamed

2021-11-16 16:15 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +const ButtonChange = (props) => {
Renamed this Button-elem

2021-11-16 16:16 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +  const { id, changeNote, callToEditNote, noteList } = props;
Deleted const and made it into func-params

2021-11-16 16:17 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +    </>
Deleted empty tag

2021-11-16 16:18 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +export const ButtonSaveChanges = (props) => {
Added new files and replace its

2021-11-16 16:18 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +export const ButtonSaveChanges = (props) => {
Done

2021-11-16 16:18 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +    <>
Done

2021-11-16 16:18 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/ActionButtons.jsx
> +          onClick={() => deleteNotes(index)}
Renamed to deleteNote

2021-11-16 16:19 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +const InputChange = ({
Separated and importing comp form new folders/files

2021-11-16 16:20 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +import { ButtonSaveChanges, ButtonDelete } from './ActionButtons';
Fixed in a few files, but i recognized that 'Eslin' make it automatically

2021-11-16 16:22 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const classes = useStyles();
There were destructure styles and fixed classNames.

2021-11-16 16:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const [newInputState, setNewInputState] = useState(description);
Renamed its

2021-11-16 16:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +  const sendNewValue = (e) => {
Fixed its also

2021-11-16 16:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/header/HeaderNav.jsx
> +    <>
Done

2021-11-16 16:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/header/HeaderNav.jsx
> +  const classes = useStyles();
Fixed

2021-11-16 16:24 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/header/HeaderNavCont.jsx
> +  <>
Done

2021-11-16 16:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +    const sortDescription = mainNotes.filter((item) => item.isActive);
destructured to object and replaced 'arr[0]....'  into 'if.. else'

2021-11-16 16:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +    <>
done

2021-11-16 16:26 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    setNoteList(() => [...actualNotes]);
Fixed

2021-11-16 16:26 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +    <>
Replaced

2021-11-16 16:27 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +                        {item.description.slice(0, SHORT_DESC.limit)}
Moved into separate file

2021-11-16 16:27 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +                    key={Math.random()}
made 'custom' keys , which based on item.id

2021-11-16 16:28 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +import React, { useState, Suspense } from 'react';
its Container

2021-11-16 16:28 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +    <>
fixed again

2021-11-17 10:02 UTC, k-krasilnikova requested changes

2021-11-17 10:02 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +        ? noteList.map((item, index) => (
We can use here optional chaining.
```suggestion
      {noteList?.map((item, index) => (
```

2021-11-17 10:02 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +        ? noteList.map((item, index) => (
Or `noteList && noteList.map..`
It's not a good practice to use `null` inside jsx

2021-11-17 10:02 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +import React, { useState, Suspense } from 'react';
Can't see any changes with name

2021-11-17 10:02 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +  const { mainContainer, spiner } = useStyles();
remove

2021-11-17 10:02 UTC, k-krasilnikova commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +const chooseNote = (itemId, matchSource) => {
Just move all of them inside one file

2021-11-17 15:11 UTC, NikitaKhadnevich commented on React_Notes_Block/src/utils/ChooseNote.jsx
> +const chooseNote = (itemId, matchSource) => {
Moved inside ChooseNote.jsx

2021-11-19 08:22 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/notes/InputChange.jsx
> +import useStyles from '../../pages/mainNotes/listNotes/styled';
On one with folder level, added wrapper-reciever for this.

2021-11-19 08:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/header/HeaderNav.jsx
> +import useStyles from './styled';
Overwrote styles

2021-11-19 08:23 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +import React, { useState, Suspense } from 'react';
Fixed

2021-11-19 08:24 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/header/HeaderNavCont.jsx
> +const HeaderNavCont = () => <HeaderNav />;
Deleted this item

2021-11-19 08:24 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +import { INITIALNOTE } from '../../../config/constants/initNoteData';
Make it

2021-11-19 08:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +  const { aboutWrapper } = useStyles();
Done

2021-11-19 08:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +import InputChange from '../../../components/notes/InputChange';
Fixed

2021-11-19 08:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +import deleteNote from '../../../utils/DeleteNote';
Done

2021-11-19 08:25 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +  } = useStyles();
Done

2021-11-19 08:26 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +  return (
Separated this block, now its Container/Component

2021-11-19 08:28 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotes.jsx
> +        ? noteList.map((item, index) => (
```suggestion
      {noteList
        ? noteList.map((item, index) => (
```
Remake notelist and added other component instead null

2021-11-19 08:29 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotesCont.jsx
> +  const { mainContainer, spiner } = useStyles();
Done

2021-11-19 09:02 UTC, NikitaKhadnevich commented
In this request I had done:

1. Added some func and styles
2. Separate Cont/Comp;
3. Created 'Wrapper-Recivers' for path to files;
4. Added Spinner for loading;
5. Fixed func and method;
6. Added constant;
7. Overwrote useStyles to Styles Comp;
8. Replace modules and folders

2021-11-25 09:25 UTC, k-krasilnikova requested changes
Good job, but still needs some updates

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  function change(name, e) {
Why it's not an arrow?

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  // confirmPassword: PropTypes.string,
Do we really need this commented code?

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/aboutPage/LazyAboutPage.jsx
> +import React from 'react';
We should rename this file to something more simple:
index.jsx

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/aboutPage/LazyAboutPage.jsx
> +const LazyAboutPage = React.lazy(() => import('./aboutPage'));
`aboutPage` inside `aboutPage`? Rewrite this structure please.

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +    const [sortDescription] = mainNotes.filter((item) => item.isActive);
What is `item`?

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +  return <AboutNoteCont aboutData={aboutData} />;
This file should be renamed as `AboutNoteContainer`, and `AboutNoteCont` -> `AboutNote`
Read please rules again. `Cont` is pretty bad word in naming

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/aboutNote/LazyAboutNotes.jsx
> +
index!

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/LazyListNotes.jsx
> +
index

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotesCont.jsx
> +import ListItem from '@mui/material/ListItem';
It's a component...
Remove `Cont` from all the places inside the application. Use `Container` instead, but in correct places!!!!!!!

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/mainNotes/mainNotes.jsx
> +const MainNotes = () => {
It's a Container

2021-11-25 09:25 UTC, k-krasilnikova commented on React_Notes_Block/src/pages/sharedNotePage/sharedNotesCont.jsx
> +const SharedNotes = () => {
It's a Component

2021-11-25 12:33 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  // confirmPassword: PropTypes.string,
Yes, I will use this prop in future. There are formik values, i will implemented or remove in next pull. Its ok? May i save this?

2021-11-25 13:46 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  function change(name, e) {
Renamed and converted to arrow

2021-11-25 13:46 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/aboutPage/LazyAboutPage.jsx
> +import React from 'react';
fixed to indexLazy.jsx

2021-11-25 13:58 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/aboutPage/LazyAboutPage.jsx
> +const LazyAboutPage = React.lazy(() => import('./aboutPage'));
Yes, Lets see. I configured this files as like in article which u sent.
I have container with some html, and i want accurate this container be lazy.
For this i sent it to React Lazy and then wrapped In suspense.
For example in future i will want to add some component without lazy-load and spinner.  Its will be easy - i will add it in Main container. In the end i will have 2 components: with lazy and without. I think its good idea. about note block in "notes" work similar. As user i wdnt see 'spinner hell'))

2021-11-25 13:59 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/ListNotesCont.jsx
> +import ListItem from '@mui/material/ListItem';
Fixed and renamed

2021-11-25 13:59 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/mainNotes.jsx
> +const MainNotes = () => {
Replaced

2021-11-25 14:00 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/sharedNotePage/sharedNotesCont.jsx
> +const SharedNotes = () => {
Fixed and renamed

2021-11-25 14:02 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/LazyAboutNotes.jsx
> +
Remove lazy from this block, Its small elem and i suppose its not good idea wrapping everything in lazy

2021-11-25 14:02 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/LazyListNotes.jsx
> +
renamed to indexLazy.jsx

2021-11-25 14:05 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/AboutNote.jsx
> +  return <AboutNoteCont aboutData={aboutData} />;
Renamed and replace path to 'App.jsx'

2021-11-25 14:38 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  // confirmPassword: PropTypes.string,
Yep, sure

2021-11-29 17:00 UTC, NikitaKhadnevich commented
Finished work with 4 Task. In this Pull i finally had fixed wrongs in files and folder and added SignUp/SignIn components, Also added new Redux actions/reducer for this and other. Also I worked with React Query (query, mutaions) and LocalStorage.

2021-11-29 17:00 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +  // confirmPassword: PropTypes.string,
Implement it in this push

2021-11-29 17:01 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/aboutPage/LazyAboutPage.jsx
> +const LazyAboutPage = React.lazy(() => import('./aboutPage'));
Fixed to index.js - style

2021-11-29 17:01 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/aboutNote/LazyAboutNotes.jsx
> +
Fixed to index.js - style

2021-11-29 17:01 UTC, NikitaKhadnevich commented on React_Notes_Block/src/pages/mainNotes/listNotes/LazyListNotes.jsx
> +
Fixed to index.js - style

2021-12-01 09:26 UTC, k-krasilnikova requested changes

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/api/sharedToolkit/sharedSelectors.js
> +export const sharedArr = (state) => state.notesShare.sharedArr;
arr, mrr, prr, brr.
Rename this variable with something more clear please

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/api/sharedToolkit/sharedSelectors.js
> +export const isShared = (state) => state.inotesShare.sShared;
seems typo here

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikIn.js
> +    </>
Remove unexpected wrapper please

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikUp.js
> +    <>
Unexpected wrapper
Also please rename this file to the: FormikUpContainer

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignIn.jsx
> +    <SignContainer component='main'>
Is it container? Or component? Separate logic from UI and create an appropriate name for them

2021-12-01 09:26 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +    <SignContainer component='main'>
Container? Component?

2021-12-01 10:41 UTC, NikitaKhadnevich commented on React_Notes_Block/src/api/sharedToolkit/sharedSelectors.js
> +export const sharedArr = (state) => state.notesShare.sharedArr;
Renamed to sharedNotes

2021-12-01 10:41 UTC, NikitaKhadnevich commented on React_Notes_Block/src/api/sharedToolkit/sharedSelectors.js
> +export const isShared = (state) => state.inotesShare.sShared;
yep , fixed

2021-12-01 10:42 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikIn.js
> +    </>
Removed

2021-12-01 10:44 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikUp.js
> +    <>
Renamed this and FormikIn => FormikUpContainer

2021-12-01 11:03 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignIn.jsx
> +    <SignContainer component='main'>
This is component, and logic had been separated before.I added this name only in styled to Material UI Component. Previously it was 'Material UI Container' and I added name which based on main elem-name (Container). For example, i see that Material UI Style name is SignContainer. This name include the  string 'Container' and i understand that  'Material UI' type is Container. Sometimes its help to identify component style without look up into styled.jsx.
I see that is not good idea and i renamed this and other names to 'Wrapper' stuff like that.

2021-12-01 11:03 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignUp.jsx
> +    <SignContainer component='main'>
Renamed to Wrapper

2021-12-03 12:07 UTC, NikitaKhadnevich commented
**_These commit include a lot of changes:_**
-	Fixed names and paths a few files;
-	Split into small large components as like _ListNotes_, _SignUp_, _SignIn_ etc.;
-	Renamed variables in some components;
-	Rewrote ‘_NoteList State_’ into ‘_NoteList fake API_’ (added new data-base for receive, save and syncing , added useQuery, useMutations also created RestAPI functions for work with this;
-	Created Input for fill new Note and created ‘Formik-logic’ for work with this;
-	Added Box-item and functions for sorting current notes;
-	Fixed some bugs, replace styles;

2021-12-08 13:41 UTC, k-krasilnikova requested changes
Update please and merge the PR

2021-12-08 13:41 UTC, k-krasilnikova commented on React_Notes_Block/src/api/RESTClient/apiConstants.jsx
> +const notesURL = 'http://localhost:3100/WAHA_NOTES';
Uppercase please!

2021-12-08 13:41 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikInContainer.js
> +  );
Move please `useQuery(` to the `src/api/auth` folder. Write your own hook ("wrapper for useQuery"  `getUsers`) and call it inside Container

2021-12-08 13:41 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikUpContainer.js
> +  const { isLoading, error, data, isFetching } = useQuery('GetUsers', () =>
!

2021-12-08 13:41 UTC, k-krasilnikova commented on React_Notes_Block/src/components/forms/SignInputs/SIgnUpBirth.jsx
> +        : ''
It's not a good practice to use empty strings, try to replace condition with `&&`

2021-12-13 13:03 UTC, NikitaKhadnevich commented on React_Notes_Block/src/api/RESTClient/RESTApi.js
> +function runPOSTuser(baseUrl, obj) {
Fixed

2021-12-13 13:03 UTC, NikitaKhadnevich commented on React_Notes_Block/src/api/RESTClient/apiConstants.jsx
> +const notesURL = 'http://localhost:3100/WAHA_NOTES';
Added Upper

2021-12-13 13:04 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikInContainer.js
> +  );
Created new Folder and ownHooks, but one of them stayed old, its contain 'onSuccess logical' (ForrmikUp) block

2021-12-13 13:05 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/FormikWrappers/FormikUpContainer.js
> +  const { isLoading, error, data, isFetching } = useQuery('GetUsers', () =>
Done

2021-12-13 13:06 UTC, NikitaKhadnevich commented on React_Notes_Block/src/components/forms/SignInputs/SIgnUpBirth.jsx
> +        : ''
Fixed

2021-12-13 13:10 UTC, merged